- name: First test
  hosts: all
  gather_facts: yes
  become: yes
  roles:
    - role: suzuki-shunsuke.docker_ce_centos
      docker_centos_state: started
      docker_centos_enabled: true
      docker_centos_users:
        - vagrant
      become: true
    - role: ansible-dockerswarm
      docker_swarm_interface: "eth1"
      become: yes
    - role: docker-swarm-setup
