---
dist: bionic
language: python
python:
  - "3.6"

sudo: required

# Cache the big Vagrant boxes
cache:
  directories:
  - /home/travis/.vagrant.d/boxes

# Enable the docker service
services:
  - docker

# Replace aufs with the vfs docker storage driver
# to prevent systemd to fail starting docker in docker.
before_install:
  - sudo sed -i 's|DOCKER_OPTS=.*|DOCKER_OPTS="-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock --storage-driver vfs"|g' /etc/default/docker
  - sudo service docker restart
  - docker info

# Install molecule and docker-py
install:
  - sudo apt-add-repository -y ppa:ansible/ansible
  - sudo apt install ansible
  - pip install tox-travis
  - sudo apt-get update && sudo apt-get install -y bridge-utils dnsmasq-base ebtables libvirt-bin libvirt-dev qemu qemu-kvm qemu-utils ruby-dev
  # Download Vagrant & Install Vagrant package
  - sudo wget -nv https://releases.hashicorp.com/vagrant/2.2.7/vagrant_2.2.7_x86_64.deb
  - sudo dpkg -i vagrant_2.2.7_x86_64.deb
  - vagrant --version
  - sudo vagrant plugin install vagrant-libvirt

# Tests all the scenarios
script:
  - ansible-lint ./ansible/
  - cd ansible/roles/ansible-docker-ce-centos/tests
  - sudo vagrant up --provider=libvirt
  - cd ../../ansible-dockerswarm
  - sudo -E env PATH=$PATH tox